env:
  POSTGRES_USER: discourse
  POSTGRES_PASSWORD: discourse
  POSTGRES_DB: discourse_test

install: |
  sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -

  sudo apt-get update -y

  sudo apt-get -y install \
    git build-essential pkg-config \
    libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libreadline-dev libssl-dev zlib1g-dev libsnappy-dev \
    gifsicle jpegoptim optipng libjpeg-turbo-progs jhead redis-server curl libtool \
    advancecomp gifsicle jpegoptim optipng pngcrush \
    libsqlite3-dev sqlite3 \
    patch ruby-dev zlib1g-dev liblzma-dev \
    postgresql postgresql-contrib libpq-dev

  wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-imagemagick
  chmod +x install-imagemagick
  sudo ./install-imagemagick

  wget -qO- https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-pngquant | sudo sh

  curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  sudo apt-get install -y nodejs
  sudo npm install -g svgo
  sudo npm install -g yarn

  wget -O ruby-install-0.7.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
  tar -xzvf ruby-install-0.7.0.tar.gz
  cd ruby-install-0.7.0
  sudo make install
  cd ..
  rm -Rf ruby-install*

  wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
  tar -xzvf chruby-0.3.9.tar.gz
  cd chruby-0.3.9/
  sudo make install
  cd ..
  rm -Rf chruby-0.3.*

  ruby-install ruby 2.6.6 --no-reinstall
  source /usr/local/share/chruby/chruby.sh
  chruby 2.6.6

  gem install bundler -v 2.1.4 --no-doc
  gem update --system
  gem install mailcatcher

  bundle config deployment 'true'
  bundle config without 'development'
  bundle config build.nokogiri --use-system-libraries
  bundle install --jobs 4

  bin/rake plugin:install_all_official
  bin/rake db:create
  bin/rake db:migrate

  bundle exec ruby script/i18n_lint.rb "config/**/locales/{client,server}.en.yml"
  bundle exec ruby script/i18n_lint.rb "plugins/**/locales/{client,server}.en.yml"

  yarn install --dev

setup:
  bundle install --jobs 4

test_suite:
  command: bundle exec rspec

  files:
    - spec/**/*_spec.rb
    
